{% set name = "collectfasta" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jasongi/collectfasta/archive/{{ version }}.tar.gz
  sha256: 375c84876f9621c7a8b15236ad0c81cc5726cd05c6bf8b64ff0a5c9aa3030fe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2,<5.1
    - django-storages >=1.6
    - typing-extensions

test:
  imports:
    - collectfasta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jasongi/collectfasta/
  summary: A fasta collectstatic command.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
