# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: collectfasta
  version: "3.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/jasongi/collectfasta/archive/${{ version }}.tar.gz
  sha256: 7022d44129eacaabb0fb16b4d0f9413a2f5c4145db59935728b775dda0d44341

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2,<5.1
    - django-storages >=1.6
    - typing-extensions

tests:
  - python:
      imports:
        - collectfasta
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: A fasta collectstatic command.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jasongi/collectfasta/

extra:
  recipe-maintainers:
    - rxm7706
